#!/bin/bash
#SBATCH -c 1
#SBATCH -t 0-00:10
#SBATCH -p short
#SBATCH --mem 4000
#SBATCH -o run_glimpse_ligate.out
#SBATCH --mail-user=alexander_gorelick@hms.harvard.edu  # Email to which notifications will be sent
#SBATCH --mail-type=ALL

## these files will be generated by this script
bcf_file="glimpse/C157N1_ligated.bcf"
bcf_cleaned_file="glimpse/C157N1_ligated_cleaned.bcf"

module load gcc/9.2.0 bcftools/1.14

if [ ! -f $bcf_file ]; then
    ## list the glimpse .bcf files for each chunk in genomic order to a text file
    ls -1v glimpse/*.bcf > glimpse/list_imputed_files.txt

    ## Run GLIMPSE_ligate to combine the phased data for each genomic chunk
    ~/.GLIMPSE2/GLIMPSE2_ligate_static --input glimpse/list_imputed_files.txt --output $bcf_file --threads 1

    # do this if GLIMPSE2 does not do it automatically
    #bcftools index $bcf_file
fi

## Next, use bcftools to subset the data for high-confidence heterozygous SNPs
bcftools view -g het -i 'FORMAT/GP>=0.90' $bcf_file | bcftools annotate -x FORMAT/DS,FORMAT/GP -O b - > $bcf_cleaned_file
bcftools index $bcf_cleaned_file
